### ISSUE TITLE
Removal of node from cluster in case ec2 is terminated

### ISSUE THREAD

**Issue by pranshumalviya** [gruntwork-io/terraform-aws-influx#29]
If an ec2 node is terminated due to an unhealthy state, ec2 cluster will automatically add a new node to the cluster to balance it. However, the addition of the new node to influxdb cluster fails as the previous node is still not removed from the cluster.

Do you support the removal of a node from influxdb cluster while the machine is getting terminated.

**Comment by brikis98** [comment]
@tonerdo @autero1 Could you look into this?

**Comment by autero1** [comment]
Will do, just submitted a PR adding myself in CODEOWNERS

**Comment by tonerdo** [comment]
@pranshumalviya what do you mean when you say "the addition of the new node to influxdb cluster fails"? Do you get an error or does the new node just fail to register?

**Comment by pranshumalviya** [comment]
@tonerdo 
The exisitng node was not removed so while adding a new node it throws an error for entitlement 
as my license is only for 2 data nodes. It fails for the third node. If there is a way to remove node while it is terminating this issue will not occur.

**Comment by pranshumalviya** [comment]
@tonerdo Can you please help with the above question.

**Comment by autero1** [comment]
Hi @pranshumalviya 

This could be handled with creating a lifecycle hook for the terminate event. The module currently does not support this. For now, you'll have to handle the removal manually.

**Comment by pranshumalviya** [comment]
@autero1 
Thanks for the response. We have started using the same.
I will close this
